# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6ae906e358e37c7eb0893d390ea09f387f046b8f9988b21949041a31e4c6fadd6dd382623b61bac90eff06f7e33ff77cbfdbbf89e68c717b7b2ae4ab0322ca

test:
  secret_key_base: 081a70cc6c43b2d517f803f1c0178eac71717a1bdfba2451b6dba8df765a1e600b3908876cc7e9498a3c28d41b2473eefecb8cfc569db5e2884da0a696841e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
